### ISSUE TITLE
SudsLibrary

### ISSUE THREAD

**Issue by debapritadas** [ombre42/robotframework-sudslibrary#16]
Hi,
I am working on Robot Framework with SudsLibrary to automated SOAP-based web services of my product.

Following is a snippet of the automated code

...........

 ${AutoDiscoveryInfoObj}=    Create Wsdl Object    ns18:AutoDiscoveryInfo

.........

${AddressRangeInfoObj}=    Create Wsdl Object    ns18:AddressRangeInfo
    Set Wsdl Object Attribute    ${AddressRangeInfoObj}    endingIpAddress    10.63.40.13
    Set Wsdl Object Attribute    ${AddressRangeInfoObj}    startingIpAddress    10.63.40.11
    ${iprange}=    Create Wsdl Object    ArrayOf_xsd_anyType
    Set Wsdl Object Attribute    ${iprange}    _arrayType    ns2:anyType[]
    Set Wsdl Object Attribute    ${iprange}    _id    ${AddressRangeInfoObj}
     Set Wsdl Object Attribute    ${AutoDiscoveryInfoObj}    includeRanges    ${iprange}

..........

Here ArrayOf_xsd_anyType is a WSDL Object type and _arrayType and _id are two of its attributes. While executing the above piece of code , the following piece of SOAP message gets generated

<?xml version="1.0" encoding="UTF-8"?> <SOAP-ENV:Envelope xmlns:ns3="http://schemas.xmlsoap.org/soap/encoding/" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:ns0="http://api.common.configmgr.powerup.com" xmlns:ns1="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns2="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns4="http://network.api.common.configmgr.powerup.com" xmlns:ns5="Urn:ApiService" xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"> SOAP-ENV:Header/ ns1:Body

...........
...........

 <includeRanges xsi:type="ns5:ArrayOf_xsd_anyType" arrayType="ns2:anyType[]"> 
 <_id xsi:type="ns4:AddressRangeInfo"> 
 <endingIpAddress xsi:type="ns2:string">10.63.40.13</endingIpAddress>
 <startingIpAddress xsi:type="ns2:string">10.63.40.11</startingIpAddress>
 </_id> 
 </includeRanges>

 ...............
 ..............

But throws errors saying "00:45:33.962  FAIL    WebFault: Server raised fault: 'org.xml.sax.SAXException: No deserializer defined for array type null"

I tried to run manually the above SOAP message in SOAPUI with little modification as follows and it passed

...........
...........

 <includeRanges xsi:type="ns5:ArrayOf_xsd_anyType" ns3:arrayType="ns2:anyType[]"> 
 <_id xsi:type="ns4:AddressRangeInfo"> 
 <endingIpAddress xsi:type="ns2:string">10.63.40.13</endingIpAddress>
 <startingIpAddress xsi:type="ns2:string">10.63.40.11</startingIpAddress>
 </_id> 
 </includeRanges>

 ...............
 ..............

 Now I want to know if there is any in-built functions in SudsLibray using which i can prefix a namespace to an attribute of a WSDL Object instance while calling Set Wsdl Object Attribute(please note by adding ns3 namespace as prefix to arrayType it worked i.e as ns3:arrayType="ns2:anyType[])... Or any other way  to do the same.. The generated SOAP message is just needed  to have the required namespace prefixed to the attribute name..

 Any suggestion would be helpful !!!!

**Comment by ombre42** [comment]
This issue was cross-posted to the Robot Framework [user group](https://groups.google.com/d/msg/robotframework-users/ILsVHo6E2V0/fUTfQ1FuqDEJ).
Looking around the web, the way to solve this seems to be by using a message plugin.
The code here should be pretty close to what you need, but the XPath needs updating as I do not see the whole structure of the request in your post.
Put the code in a file called `SudsLibraryExtensions.py` in the same directory as your resource file.
Add it to your resource file:
`Library           SudsLibraryExtensions.py`

After creating the SOAP client, add a call to `Attach My Plugin`.
When the request is about to be sent, the plugin will remove the `arrayType` attribute and add it back as `ns3:arrayType`. It may take a little experimentation to get it working.

```
from robot.libraries.BuiltIn import BuiltIn
from suds.plugin import MessagePlugin


class _MyPlugin(MessagePlugin):
    def marshalled(self, context):
        root = context.envelope
        element = root.childAtPath("Body/SomeRequest/includeRanges")
        child = element.children[0]
        array_type_value = child.get('arrayType')
        if array_type_value:
            child.unset('arrayType')
            child.set('ns3:arrayType', array_type_value)

class SudsLibraryExtensions(object):
    def attach_my_plugin(self):
        client = BuiltIn().get_library_instance("SudsLibrary")._client()
        # prepend so SudsLibrary's plugin is left in place
        plugins = client.options.plugins
        if any(isinstance(x, _MyPlugin) for x in plugins):
            return
        plugins.insert(0, _MyPlugin())
        client.set_options(plugins=plugins)
```
