### ISSUE TITLE
The code failed to compile in jython 2.5

### ISSUE THREAD

**Issue by stevez** [ombre42/robotframework-sudslibrary#20]
When I tried to use Jython 2.5 to compile the code, I got the following errors:
Compiling sudslibrary\SudsLibrary__init__.py ...
  File "C:\jython2.5.3\sudslibrary\SudsLibrary__init__.py", line 17

   ^
SyntaxError: 'import *' not allowed with 'from .'

Compiling sudslibrary\SudsLibrary\clientmanagement.py ...
  File "C:\jython2.5.3\sudslibrary\SudsLibrary\clientmanagement.py", line 21

   ^
SyntaxError: 'import *' not allowed with 'from .'

Compiling sudslibrary\SudsLibrary\factory.py ...
Compiling sudslibrary\SudsLibrary\monkeypatches.py ...
Compiling sudslibrary\SudsLibrary\options.py ...
  File "C:\jython2.5.3\sudslibrary\SudsLibrary\options.py", line 21

   ^
SyntaxError: 'import *' not allowed with 'from .'

Compiling sudslibrary\SudsLibrary\proxy.py ...
  File "C:\jython2.5.3\sudslibrary\SudsLibrary\proxy.py", line 17

   ^
SyntaxError: 'import *' not allowed with 'from .'

Compiling sudslibrary\SudsLibrary\soaplogging.py ...
  File "C:\jython2.5.3\sudslibrary\SudsLibrary\soaplogging.py", line 19

   ^
SyntaxError: 'import *' not allowed with 'from .'

Compiling sudslibrary\SudsLibrary\utils.py ...
Compiling sudslibrary\SudsLibrary\version.py ...
Compiling sudslibrary\SudsLibrary\wsse.py ...
  File "C:\jython2.5.3\sudslibrary\SudsLibrary\wsse.py", line 15

   ^
SyntaxError: 'import *' not allowed with 'from .'

I want to use the sudslibrary in Java environment, and robotframework uses Jython 2.5,  which means if we want to sudslibrary works in java environment, it needs support Jython 2.5.

**Comment by ombre42** [comment]
Thank you for reporting this.

**Comment by ombre42** [comment]
I've resolved the import issues, but uncovered a much more serious issue. Jython's socket handling has been broken from 2.5 through 2.7b2. I will probably have to copy some code over from suds-jurko to fix it, since it is affected as well. Just want to let you know I am still working on it.

**Comment by ombre42** [comment]
The world has moved on to Jython 2.7. Closing this.
